### ISSUE TITLE
Add an "Activities" entry in the menu

### ISSUE THREAD

**Issue by acrepet** [Ninja-Squad/globe42#104]
We have 5 activities:
- cours Français ET informatique
- médiation sociale
- médiation santé
- repas
- atelier droits sociaux
- atelier santé
- atelier ephemere
- atelier divers

we can have an enum for these activities (it's not mandatory to have a menu to manage them).
we have to link the person to one or several activities

we could use these icons : 
![repas_c](https://user-images.githubusercontent.com/544206/30783459-9c5c0386-a143-11e7-9573-d32661760d51.png)
![repas](https://user-images.githubusercontent.com/544206/30783460-9c5d1366-a143-11e7-935a-317433aabc74.png)
![mediation_c](https://user-images.githubusercontent.com/544206/30783461-9c5ec44a-a143-11e7-90c9-faf3329cfa5a.png)
![mediation](https://user-images.githubusercontent.com/544206/30783462-9c5fa8ce-a143-11e7-9cc0-5455257db64d.png)
![info_c](https://user-images.githubusercontent.com/544206/30783464-9c62b0b4-a143-11e7-8406-9d447952275f.png)
![info](https://user-images.githubusercontent.com/544206/30783463-9c602290-a143-11e7-9b82-cd597e4c497b.png)
![doctor_c](https://user-images.githubusercontent.com/544206/30783465-9c6e2d7c-a143-11e7-94c8-923b55cbab22.png)
![doctor](https://user-images.githubusercontent.com/544206/30783466-9c709c60-a143-11e7-8c87-89851773b50e.png)
![course_c](https://user-images.githubusercontent.com/544206/30783467-9c7202ee-a143-11e7-9299-32022defa3d9.png)
![course](https://user-images.githubusercontent.com/544206/30783468-9c73b490-a143-11e7-8271-bba68c1a266b.png)

**Comment by jnizet** [comment]
Are the "médiation sociale" and "médiation santé" linked to the flag "mediationEnabled" that already exists on a person? I.e. can a person with this flag set to false participate in these two activities, and vice versa? Or do we consider those two things as unrelated?

Also, what exactly is needed. Only to know what activities a person participates to? Or the list of persons who participate to an activity? Or both? Nothing more?

**Comment by acrepet** [comment]
I think that "médiation sociale" and "médiation santé" are effectively linked to the flag "mediationEnabled" ie
 a person without a flag "mediationEnabled" set to true can't follow these two activities.

I think that we have to : 
- manage the activities a person participates to
- and the list of persons who participate to an activity
