### ISSUE TITLE
Is it possible to assign a task to more than one person?

### ISSUE THREAD

**Issue by acrepet** [Ninja-Squad/globe42#171]

**Comment by jnizet** [comment]
I'm really not sure it's a good idea. To me, if a task is assigned to more than 1 person, every assignee will basically think: 

> the other one will do it. 

Or will think

> I'd do this, but maybe the other one has already started doing it, so should I really? Let's wait.

I think we should convince them that, if a task needs to be assigned to two persons, then it should 
 - be reassigned to the second one if/when then first one can't do it, 
 - or be assigned to a first person to to half of the task, and then assigned to the other one to do the other half
 - or be split in several subtasks, that only one person is responsible of doing

@acrepet Have you talked with Globe about that, and about these (better, IMO) workflows? What do you think? And if you have talked about these workflows, what was their reaction?

**Comment by acrepet** [comment]
They just asked me this feature by Trello. I didn't talk with them deeply about this. I can do it...
At first I thought that it could be like in Trello or GitHub (several users can manage the tasks), but yes you're right it could be a trap and a good reason to never treat the task (like in Trello) ;-)

**Comment by acrepet** [comment]
I close this issue : it could be a trap, so not a good idea!
