### ISSUE TITLE
Add like an "autosaving" feature for a note

### ISSUE THREAD

**Issue by acrepet** [Ninja-Squad/globe42#172]
We can add an actvicity for a person without having to submit a "save" button, it could be nice to have this feature (something like the `ngModelChange`  for the selection of activities) when we add a note an a person. The Globe42 members said that they often forget to click on the "save" button when they're filling a note (so often, they lose their content ;-( )

**Comment by jnizet** [comment]
This is a more complex situation than simply checking checkboxes, and I'd prefer not going to this direction, but I could add a CanDeactivate guard, that would display a confirmation modal dialog before leaving the page if a note is currently being edited. This would be easier, simpler, and would teach them to save before leaving

**Comment by acrepet** [comment]
this is perfect!
