### ISSUE TITLE
Update the Tax Situation

### ISSUE THREAD

**Issue by acrepet** [Ninja-Squad/globe42#173]
1/ Add : "n° fiscal"
2/ Delete "Date de mise en place" if "Imposable" or "Non Imposable" is selected.
They don't care about this information

**Comment by acrepet** [comment]
The Deletion of the "Date de mise en place" :+1: 
But aout the "n° fiscal" which must have 13 numbers : 
If I fill less than 13 numbers :+1:  (I have a nice validation message) but if I fill more than  13 numbers I have an exception error : "Une erreur technique inattendue s'est produite. Essayez de recharger la page. 
400 - Validation failed for object='personCommandDTO'. Error count: 1"

**Comment by jnizet** [comment]
@acrepet Good catch. I added a commit in the PR.
