### ISSUE TITLE
Add new informations for a person

### ISSUE THREAD

**Issue by acrepet** [Ninja-Squad/globe42#175]
**Only for person under mediation** : 

- [x] Add the Citizenship of the informations of a person
Having a Typeahead (as we have in the cities) could be great!

- [x] In the section "Santé" we have to refactor the "couverture médicale":
"Couverture médicale" -> couverture médicale de base" 
"Mutuelle" -> "couverture médicale complémentaire "

The field "couverture médicale de base" is a list of 7 items. In the current version of the application, we had already 7 choices but slightly different (the old name is on parenthesis). The right ones must be, and in this order:
- Inconnue
- Régime Général
- Protection Universelle Maladie (Couverture Maladie Universelle)
- Régime agricole (Régime agricole MSA)
- Aide médicale de l'Etat 
- Sécurité sociale des indépendants (Régime social des indépendants)
- Autre (Régime Spécial)

The 2nd field : " couverture médicale complémentaire " is the health Insurance. In the current version of the application, we had an input text (with a placeHolder "Mutuelle") -> now we have to have a list with these items :
- Inconnue
- Cmu-c 
- Aide Médicale Etat 
- Aide à la Complémentaire Santé 
- Mutuelle privée 

For information, In the production database, the majority of health insurance are null (or empty string) unless 3 (2= CMUC which has to stay CMUC / 1 = Eovie which has to become "Mutelle privée")

- [ ] Add a new section : SEJOUR (like LOGEMENT) with 5 items 
*Date entrée en France* (whICh is under Mediation in the current version of the application)
*Type de visa* : "C court séjour" (less than 90 days) / "D long séjour" (90 days and more)
*Type de carte de séjour* 
*Date de depot*
*Date de renouvellement*
(do not indicate : Entrée régulière / non régulière)

*Type de carte de séjour* could be : 
- Récépissé de demande de 1iere carte de séjour
- Récépissé de renouvellement de carte de séjour
- Carte mention " retraite"
- Carte de résident de 10 ans 
- Carte de séjour temporaire "vie privée et familiale" 
- Autre 

- [x] Add a new section : Réseau (like LOGEMENT) with 3 items
Personne à prévenir : 
Aidants (Famille, Voisins, ...) :
Médecin :
Assistante sociale 
Avocat : 
Autres :

**Comment by jnizet** [comment]
What if the person comes, for example, from a European country (like Romania). AFAIK, no visa is needed then. So shouldn't we have the nationality, and a "Type de séjour" select box (or radio buttons), with the  values "Entrée irrégulière", "Aucun visa nécessaire", "Visa cours séjour" and "Visa long séjour"?

**Comment by acrepet** [comment]
I asked yesterday the question to Malika!

**Comment by acrepet** [comment]
I've updated the description

**Comment by jnizet** [comment]
I think I could start working on the "network" feature. If I understand correctly, the goal is to be able to contact people in the network of the person. So I guess we need more than just a name. We probably need a name (mandatory), a phone number (optional), maybe an address (optional) and an email (optional), and even maybe some note (like when to contact the person, or any additional info that could be useful), right?

In any case, I would like to stop cluttering the main person page/edit page. So I think we should do the same thing as for the resources and the wedding events: add a new section, and allow adding / deleting / updating contacts, where each contact would have a type (doctor, lawyer, etc.) and all the above information.  

Does that look right to you?

Also, the current "contact" section has an accompanying field, which I don't really understand what it's for. Shouldn't it be one of these contacts of the new network section? 

Same question for the host_name field.

**Comment by acrepet** [comment]
Yes you could start working on the "network" feature. You've got it : the goal is to be able to contact people in the network of the person. But the "network" is more a professional network for Globe4 rather tahn a personal one, we could understand this network as the people in the network of the person who can help this person (as a lawyer, a doctor, etc.) Even if some notes or extra information could be usefull for Globe42 to contact these people, I think that we could keep is very simple with a unique text field, (they could enter whatever they think is useful)

:+1:  to stop cluttering the main person page/edit page. 

:+1: to do the same thing as for the resources and the wedding events: add a new section, and allow adding / deleting / updating contacts. But each contact does not need IMHO to have a type (doctor, lawyer, etc.) 

The accompanying field matches with then person who comes at Globe42 with the migrant (ex : a neighbor, a friend, ....), this person is not one of these contacts of the new network section?

The host_name is the name of person who is offerng eventually for now a bed for the migrant

**Comment by jnizet** [comment]
> But each contact does not need IMHO to have a type (doctor, lawyer, etc.)

Isn't that the whole point of this request? I quote you:

> Add a new section : Réseau (like LOGEMENT) with 3 items
> Personne à prévenir :
> Aidants (Famille, Voisins, ...) :
> Médecin :
> Assistante sociale
> Avocat :
> Autres :

**Comment by acrepet** [comment]
I'm doing the "SEJOUR" section
