### ISSUE TITLE
Tracking of the weddings for a person

### ISSUE THREAD

**Issue by acrepet** [Ninja-Squad/globe42#178]
We have to record all the weddings for a person and to track the date(s) of the wedding(s) and the date(s) of the divorce(s).

**Comment by jnizet** [comment]
Seriously?

I'm sure this information can be useful in some cases, but I think storing this information in a structured way, and having a complex page to add wedding and divorce dates is overkill. Can't they just add a note to the person when this information is necessary?

**Comment by acrepet** [comment]
seriously ;-)
I don't know why is so useful for them, but they've really explained me that it's usefull. I propose them the "note" alternative... and waitinf their answer

**Comment by jnizet** [comment]
OK, I have some free time, so I'll do it. But do we agree that we just want to know about weddings and divorces? No Pacs/DePacs? No end of marriage due to widowhood?

**Comment by acrepet** [comment]
I've tested :+1: 
I think that it's sufficient just having weddings and divorces and no Pacs/DePacs, end of marriage due to widowhood, etc.
I'm just wondering if they want to have for each wedding the name of the spouse. But leave it like this, we'll discuss about that point with Malika soon (I hope so, she's definitely overburdened with work ;-( )
