### ISSUE TITLE
Manage the adhesion yearly

### ISSUE THREAD

**Issue by acrepet** [Ninja-Squad/globe42#259]
Currently Globe has 1 excel file  to store their members per year. They would like not to have to complete this excel file in addition to the membership card.
The application could store it! And the application could generate a pdf to print with the pre-fill fields.
At each beginning of new year, it's not possible to toggle the members of the previous year as members of the new year, because each member has to pay back his membership, otherwise he is no longer considered a member.
We can have a dedicated tab in the vizuallisation of the member data (like Ressources, Situation Familiale, etc.) which could indicate the historic of his adhesions.
For the member edition, we can add a new ADHESION section (like LOGEMENT), with these items: 
- Paiement des 5 euros : OUI / NON
- Mode de réglement : espèce -chèque 
- Date 
- Numero de carte (each membership paper card as a number)

and we can add a button : "generer le formulaire d'adhesion" with all the pre-filled fields (see the document below). Globe has to print it, the member has just to sign it, Globe could then scan this paper and add it in "Documents" section of a member!
[FICHE_ADHESION_GLOBE_version_definitive.pdf](https://github.com/Ninja-Squad/globe42/files/1958174/FICHE_ADHESION_GLOBE_version_definitive.pdf)

**Comment by jnizet** [comment]
We need to discuss about that, because I don't understand the workflow.

**Comment by acrepet** [comment]
no problem ;-)
it's to late for you?
