### ISSUE TITLE
handle errors such as failure to create a user or person due to a conflict

### ISSUE THREAD

**Issue by jnizet** [Ninja-Squad/globe42#47]
Options:
 - deal with them in the component
 - deal with them in a generic way, using an interceptor

In any case, there are other choices to consider:
 - generate error messages, in French, on the backend, and display them as is on the frontend
 - or add an error key, along with potential parameter values needed by the frontend to display a meaningful message, to the error response bodies, and use the key and the parameters to create an error message on the frontend

The former is simpler and faster, but puts presentation concerns in the backend, and doesn't allow for i18n of course (but we don't care, right?)
The latter is cleaner, but needs a little bit more work.

Other questions:

 - if we use an interceptor (which we probably should, at least to catch unexpected errors), where do we display the errors?
 - if we use an interceptor to handle expected functional errors, how do we deal with exceptions, i.e. cases where the error shouldn't be displayed, because the component must deal with it in a specific way (think about a validator which makes requests to see if it gets a 404, for example). Since the component can't pass anything safely (other than using a header, which is ugly) to the interceptor, AFAIK, we could use a list of exceptions (URL + method + status) in the interceptor.

@cexbrayat @acrepet what do you think?

**Comment by acrepet** [comment]
"The former doesn't allow for i18n of course (but we don't care, right?)" -> currently, we don't care. But perhaps one day, some arabic (or people of other origins) volunteers or employees (who speak French but not really write it) would want to use the app... Malika hopes in the future to make up of an equal number of French employees and migrant employees!

IMHO -> using an interceptor is a good idea

**Comment by jnizet** [comment]
The good news is that the design I implemented allows for i18n. The bad news is that i18n would have an impact on basically every page, and also on the design of some services. And arabic is one of the hardest things to handle, because it's right-to-left, and very hard to check if done right. So I sure hope that if migrants start using the app (which should be really cool), they'll use French, or maybe English :-)

**Comment by acrepet** [comment]
No problem, this eventuality is really not sure!
And yes, they could use French (not English for sure :-) !)

**Comment by acrepet** [comment]
"if we use an interceptor to handle expected functional errors" -> you've written an interceptor for both functional and technical exceptions, right? 

"think about a validator which makes requests to see if it gets a 404, for example" -> sorry for the nitpicking, but for this example It would be better a 400 (bad request), no?

**Comment by jnizet** [comment]
@acrepet No. Currently, the functional errors are not handled by the interceptor. They must be handled by the components, which can thus choose whatever they want to do with them (but need to handle them somehow, or they wouldn't be displayed anywhere). 

If the component wants to handle the functional error in the classical way, however (i.e. by displaying it in the alert on the right), it's very easy because all it has to do is `subscribe(success, this.errorService.funtionalErrorHandler())`. 

I'm not very happy with that situation, because I would prefer to not have to do anything, and let the interceptor o that by default. The problem with that approach is that there is currently no clean way to tell the interceptor: "hey, ifyou get a functional error for this request, don't handle it, I'll do it the way I want to". I hope it will become possible, though: see https://github.com/angular/angular/issues/18155. When it is, then the interceptor can handle all errors, except the ones for which the component signals that they shouldn't.

Regarding the validator, it all depends on what the validator does. A typical use-case (that I had in mind), consists in checking, for example, that the login of a user that we're about to create is not used by another user yet. To do its job, the validator would do a request to get the user with the entered login, and the proper status for the response would be 404: I haven't found any user with that login.

**Comment by acrepet** [comment]
OK, I got it! Thanks for giving me these clear explanations ! I wasn't familiar at all with with this issue angular/angular#18155
