### ISSUE TITLE
[Back] Add a Ressource Entity

### ISSUE THREAD

**Issue by acrepet** [Ninja-Squad/globe42#6]
A Ressource is a Financial Ressource for a Person.

We could define an entity with :
- the name of the ressource (ex: APL, Agric/Arrco, Invalidité)
- the type of the ressource (ex: CAF, Retraite, Pole Emploi, Sécurité Sociale, ... )
- the maximum mensual amount (ex : 810,89 euros for AAH)

A Person could have a lot of Ressources.
A Ressource could be given at a lot of people.
We have a Many-to-Many relationship between Person and Resource.
Because we have to add an extra information on this relationship (amount), we can map it, add an Entity PersonResource with : 
- an attribute called _resource_ annotated with @ManyToOne @PrimaryKeyJoinColumn
- an attribute called _person_ annotated with @ManyToOne @PrimaryKeyJoinColumn
- amount (the amount of the resource for the person)

**Comment by jnizet** [comment]
Given that resource is already a widely used technical term, I suggest naming the entities IncomeSource (source de revenu) and Income. I also hate composite keys with a passion, so I'll go with a traditional autogenerated key for the Income.

**Comment by acrepet** [comment]
ok! perfect!
