### ISSUE TITLE
add neighborhood on Person

### ISSUE THREAD

**Issue by acrepet** [Ninja-Squad/globe42#81]
We have to add a new information in the Person form : his/her district / neighborhood (Carnot, Beaubrun, Chavanelle, ... for Saint-Etienne for example) and just for some cities  : Saint-Etienne, Saint-Chamond, L'Horme, Le Chambon Feugerolles, Firminiy, Unieux.

As @jnizet did for #67 we would use a free dataset to populate our database with cities...
For Saint-Etienne, the [dataset](http://sig.ville.gouv.fr/tableaux/exportTableauIris/codezone/42218/tableCode/ind211) is freely available, in CSV format (from data.gouv.fr) but I found some problems about the quality of these data : for example some district names are wrong in the dataset: 
Chataucreux -> ChatEaucreux
;-(
We have these free datasets for the other cities : [Saint-Chamond](https://www.data.gouv.fr/fr/datasets/presence-dans-la-commune-d-une-zone-urbaine-sensible-zus-30382883/), [Le Chambon Feugerolles](http://sig.ville.gouv.fr/Territoire/42044/onglet/DonneesLocales), [Firminy](http://sig.ville.gouv.fr/Territoire/42095/onglet/DonneesLocales), [Unieux](http://sig.ville.gouv.fr/Territoire/42316/onglet/DonneesLocales) **except L'Horme**.

Another hassle : we have to know if a district is among the "QVP districts" (_quartiers prioritaires réglementaires_) or the "QVA districts" (_quartiers veille active_)  and there is not these information in the free dataset.

Extract of a [legal text](http://www.saint-etienne-metropole.fr/fileadmin/user_upload/03_pres_de_vous/votre_quotidien/solidarite/Contrat_de_ville/Contratdeville2015-2020.pdf) :
**Les périmètres des 15 QPV reconnus par l’État sont fixés par le décret n° 2014-1750 du 30 décembre 2014 pour la métropole de Saint-Etienne. Ils peuvent bénéficier de la mobilisation préalable du droit commun, des crédits politique de la ville de tous les financeurs du contrat de ville et de tous les avantages automatiquement associés à ce statut. Ces quartiers stéphanois sont QVP : 
La Cotonne/Montferré
Crêt de Roc/Soleil
Montreynaud
Quartiers Sud-Est
Tarentaize/Beaubrun
Terrenoire 

Les 15 quartiers « en veille active » (QVA) également reconnus par l’État ne peuvent plus bénéficier des crédits spécifiques de l’État au titre de la politique de la ville mais sont identifiés comme rencontrant des difficultés. A ce titre, ils pourront bénéficier d’un accompagnement technique et/ou d’un soutien financier au titre du droit commun pour l’État et des crédits politique de la ville des autres partenaires signataires du contrat de ville. Ces quartiers stéphanois sont QVA : 
Chavanelle-Saint-Roch
La Dame blanche
Solaure
Soleil
Tardy
"

My proposal is to populate manually a _district_ table with something like that for the columns : 
- name
- id_postal_city
- QVP (boolean)
- QVA (boolean)

**Comment by acrepet** [comment]
Yesterday at the demo with Malika, from Globe, she said us that it could be nice to know if an address matches to a district QVP or QVA. Malika has to give us the URL she uses to know that. Perhaps we could integrate an open API

**Comment by acrepet** [comment]
this is the website used by Malika : [](https://sig.ville.gouv.fr)

Here is a form to know if an address matches with a QVP (I have not yet the information for QVA)
 : https://sig.ville.gouv.fr/recherche-adresses-qp-polville
the request is a POST with few parameters :  
insee_com (hidden, fixed -> 69091)
code_postal
nom_commune
num_adresse
id_voie (hidden)
nom_voie

**Comment by jnizet** [comment]
I have tried playing a bit with this shitty form, and I really don't think we can automate anything, except adding a link to open the page in a new tab. It requires not only the postal code, but also the city, with exactly the same case as they expect, and same for the other fields. There doesn't seem to be a way to prepopulate the form, and it only returns HTML, which would be horrible to parse safely.

**Comment by cexbrayat** [comment]
I did not really follow, but can't we do the same as we did for the address, build our own API based on open data? Something like https://www.data.gouv.fr/fr/datasets/quartiers-prioritaires-politique-de-la-ville/ ?

**Comment by jnizet** [comment]
That would be ideal. I didn't know that existed, and have no idea if it's the same dataset as the one used by the link posted by Agnès. But even if we do that, that's not an easy task: we would have to geolocate the address, then test if the geolocation is inside one of the polygons inside the file. It's certainly doable using google maps APIs, but it won't be a piece of cake. It can be fun to try doing it, but maybe we should start by something simpler.

**Comment by cexbrayat** [comment]
I can't find the data for Loire, Rhone-Alpes or France anyway, it seems that only some cities and departments have uploaded theirs...

**Comment by acrepet** [comment]
Yes, I have found these data from data.gouv but you don't have the same for
St-Etienne and its suburbs. I've sent last Tuesday an email to the team of
sig.gouv.fr
I'm waiting for their answer.
Agbes'

Le 11 août 2017 1:57 PM, "Cédric Exbrayat" <notifications@github.com> a
écrit :

I can't find the data for Loire, Rhone-Alpes or France anyway, it seems
that only some cities and departments have uploaded theirs...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Ninja-Squad/globe42/issues/81#issuecomment-321794304>,
or mute the thread

**Comment by acrepet** [comment]
For the moment, we can't automate the filling of the form or we can't request an Open API (the magic world of open data :-1:  ) so for the first iteration of this task we could just add a link to open the page in a new tab.

**Comment by acrepet** [comment]
The magic of Twitter : I sent a tweet to data.gouv.fr and few hours after I had the answer :https://twitter.com/agnes_crepet/status/896380116640681984?s=09

They have an API in beta :

https://etalabapi-quartiers-prioritaires-hornzrkvrj.now.sh/quartiers-prioritaires?lat=49.116425128219795&lon=6.223948001861572

"Il faut chaîner avec un appel à l’API de géocodage https://t.co/MKIHCikLBT "
"On va rajouter un paramètre permettant de définir une tolérance, en mètres, car l’adresse n’est pas toujours correctement positionnée."

**Comment by acrepet** [comment]
I've tested these APIs. I've chosen 2 addresses:
- the first one matches to a QV (quartier prioritaire) : 30 Boulevard Antonio Vivaldi 42000 SAINT-ETIENNE
- the second one doesn't match a QV : 10 avenue de la libération 42000 SAINT-ETIENNE

I've chained the two APIs, firstly the API of adresses search (`https://api-adresse.data.gouv.fr/search`) and then the beta API of QV (`https://etalabapi-quartiers-prioritaires-hornzrkvrj.now.sh/quartiers-prioritaires`):

For the first address : 
call this URL : https://api-adresse.data.gouv.fr/search/?q=10%20avenue%20de%20la%20liberation%2042000%20SAINT-ETIENNE
return : 
`{"version": "draft", 
  "features": [{
        "geometry": {"type": "Point", "**coordinates": [4.39203, 45.437121]**},
        "type": "Feature",
        "properties": {"id": "ADRNIVX_0000000279715616", "importance": 0.3333, "name": "10 Avenue de la Lib\u00e9ration", "postcode": "42000", "housenumber": "10", "citycode": "42218", "x": 808829.6, "label": "10 Avenue de la Lib\u00e9ration 42000 Saint-\u00c9tienne", "y": 6482924.6, "street": "Avenue de la Lib\u00e9ration", "context": "42, Loire, Auvergne-Rh\u00f4ne-Alpes (Rh\u00f4ne-Alpes)", "type": "housenumber", "city": "Saint-\u00c9tienne", "score": 0.939390909090909}
  }],
  "licence": "ODbL 1.0",
  "attribution": "BAN",
  "query": "10 avenue de la liberation 42000 Saint-etienne",
  "type": "FeatureCollection",
  "limit": 5
}`

**Comment by acrepet** [comment]
Remember that firstly we had to know if a district is among the "QV" (quartiers prioritaires) or the "QVA" (quartiers veille active). But I had a last information from Malika : she only needs to know if an address matches a QV but not a QPA (she never searches this information from the [website](https://sig.ville.gouv.fr/recherche-adresses-qp-polville) she gave us). This is a good thing, because we don't have this information form data.gouv.fr ;-)
