### ISSUE TITLE
add Healthcare Cover & Health Insurance on Person

### ISSUE THREAD

**Issue by acrepet** [Ninja-Squad/globe42#82]
For each person, we have to know: 
- his/her Healthcare Cover (_Couverture medicale_ in French : 
    _Regime Général_ (for the employees)
    _Régime Agricole_ (for the agricultural workers, payed by the MSA - _Mutuelle Sociale Agricole_)
    RSI (_Regime Social des indépendants_)
    AME (_Aide médiale de l'Etat_ - usually for people without papers)
    CMU (_Couverture Médicale Universelle_ - usually for people with papers but without sufficient incomes)
    SPECIAL (_régimes spéciaux_ : _SNCF, RATP, EDF-GDF, Banque de France, Assemblée nationale, Sénat,_ ...)

- his/her Health Insurance  (_Mutuelle in French_ : AXA, MGEN, ...)

**Comment by jnizet** [comment]
Is this done now @acrepet

**Comment by acrepet** [comment]
I've done the Healthcare Cover, but I have to add the Health Insurance
