### ISSUE TITLE
consider adding the mediation code in the full name pipe

### ISSUE THREAD

**Issue by jnizet** [Ninja-Squad/globe42#92]
This should be a fairly easy ask if you want to start coding something @acrepet.

**Comment by acrepet** [comment]
I'm not sure to have understood. Is it still current?

**Comment by jnizet** [comment]
They haven't asked for it. In the beginning, they told us they referred to persons using their mediation code. But it isn't even displayed whenever we have a reference person (for example when a task concerns a person). So it's a bit contradictory. But if they don't complain, I guess we can just close this.
